version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - DARAJA_CONSUMER_KEY=${DARAJA_CONSUMER_KEY}
      - DARAJA_CONSUMER_SECRET=${DARAJA_CONSUMER_SECRET}
      - AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
      - AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - easyconnect-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - easyconnect-network

networks:
  easyconnect-network:
    driver: bridge